apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: paleo-cloud
  name: paleo-cloud
spec:
  replicas: 16 # number of pods to run
  selector:
    matchLabels:
      run: paleo-cloud
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 10
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: paleo-cloud # metadata label attached to pod
    spec:
      containers:
        - image: bdpedigo/paleo-cloud:v7 # image to pull from dockerhub
          name: paleo-cloud # name of container in pod
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "while true; do uv run runners/extract_info_2024-11-13.py; done"]
          env:
            - name: CLOUDSDK_CORE_PROJECT
              value: ${CLOUDSDK_CORE_PROJECT}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/root/.cloudvolume/secrets/google-secret.json" #TODO
            - name: VERBOSE
              value: "true"
            - name: OPENBLAS_NUM_THREADS
              value: "1"
            - name: MKL_NUM_THREADS
              value: "1"
            - name: NUMEXPR_NUM_THREADS
              value: "1"
            - name: OMP_NUM_THREADS
              value: "1"
            - name: QUEUE_NAME
              value: "ben-paleo"
            - name: RUN
              value: "true"
            - name: N_JOBS
              value: "1"
          resources:
            requests:
              # memory: 0.18Gi
              # cpu: "90m"
              memory: 0.3Gi
              cpu: "100m"
            limits:
              memory: 2.0Gi
          volumeMounts:
            - name: secrets-volume
              mountPath: /root/.cloudvolume/secrets
      dnsPolicy: Default
      volumes:
        - name: secrets-volume
          secret:
            secretName: secrets